[build]
  base = "."
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.googleapis.com *.googletagmanager.com; style-src 'self' 'unsafe-inline' *.googleapis.com; img-src 'self' data: *.unsplash.com *.googleapis.com; connect-src 'self' *.googleapis.com *.razorpay.com; font-src 'self' *.googleapis.com *.gstatic.com;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Performance optimizations
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true

# Environment-specific configurations
[context.production.environment]
  NODE_ENV = "production"
  VITE_ENABLE_ANALYTICS = "true"
  VITE_ENABLE_ERROR_REPORTING = "true"

[context.deploy-preview.environment]
  NODE_ENV = "staging"
  VITE_ENABLE_ANALYTICS = "false"
  VITE_ENABLE_ERROR_REPORTING = "false"

[context.branch-deploy.environment]
  NODE_ENV = "development"
  VITE_ENABLE_ANALYTICS = "false"
  VITE_ENABLE_ERROR_REPORTING = "false"

# Functions configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Dev server configuration
[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"
  autoLaunch = false
